create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table order_product (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table order_user (user_id bigint, order_id bigint not null, primary key (order_id)) engine=InnoDB;
create table orders (id bigint not null auto_increment, address varchar(255), date datetime, email varchar(255), last_name varchar(255), name varchar(255), price integer, primary key (id)) engine=InnoDB;
create table product (id bigint not null auto_increment, amount integer, description longtext, discount bit, image_url varchar(255), name varchar(255), price integer, recent bit, primary key (id)) engine=InnoDB;
create table product_category (product_id bigint not null, category_id bigint not null, primary key (product_id, category_id)) engine=InnoDB;
create table review (id bigint not null auto_increment, date date, product_id bigint, review longtext, primary key (id)) engine=InnoDB;
create table review_product (product_id bigint, review_id bigint not null, primary key (review_id)) engine=InnoDB;
create table review_user (user_id bigint, review_id bigint not null, primary key (review_id)) engine=InnoDB;
create table role (id bigint not null auto_increment, role varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, active integer, address varchar(255), confirmation_token varchar(255), email varchar(255), lastname varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table order_product add constraint FKhnfgqyjx3i80qoymrssls3kno foreign key (product_id) references product (id);
alter table order_product add constraint FKl5mnj9n0di7k1v90yxnthkc73 foreign key (order_id) references orders (id);
alter table order_user add constraint FK7u87v2jn4jiwxwlnw9krj36u7 foreign key (user_id) references user (id);
alter table order_user add constraint FKm7muior2ynl30n8qh9yqembso foreign key (order_id) references orders (id);
alter table product_category add constraint FKkud35ls1d40wpjb5htpp14q4e foreign key (category_id) references category (id);
alter table product_category add constraint FK2k3smhbruedlcrvu6clued06x foreign key (product_id) references product (id);
alter table review_product add constraint FK2epbpsjll2ucuabh1dn26ivtq foreign key (product_id) references product (id);
alter table review_product add constraint FK4k46hhvvftg19m1x4dies89ia foreign key (review_id) references review (id);
alter table review_user add constraint FK4w3pbu40j6452vavsjcqqugmy foreign key (user_id) references user (id);
alter table review_user add constraint FK8m6ou69fl8wsnp7dmg9biod6n foreign key (review_id) references review (id);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
